name: Build GraphQL exporter

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ricardbejarano/graphql_exporter

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5

    - name: Build
      run: make

    - name: upload binary
      uses: actions/upload-artifact@v2
      with:
        name: graphql_exporter
        path: bin
