name: Build initrd for Debian Bullseye netboot install

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download bullseye initrd
        run: curl -OL https://ftp.gwdg.de/pub/linux/debian/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
      
      - name: Unzip initrd
        run: gunzip initrd
      
      - name: create directory
        run: mkdir ramdisk
      
      - name: extract initrd files to ramdisk folder
        working-directory: ./ramdisk
        run: sudo cpio -id < ../initrd
        
      # Problem: If we send a SIGTERM to dhcp6c, it will release our IPv6 address we received via DHCPv6
      # Fix: Instead of sending a SIGTERM, we directly send a SIGKILL
      # because all DHCP agents must be stopped for the installer to proceed.
      - name: update kill-all-dhcp file
        working-directory: ./ramdisk
        run: sudo sed -i s/-TERM/-KILL/g bin/kill-all-dhcp

      - name: Build the new initrd
        working-directory: ./ramdisk
        run: |
          echo "INITRD_VERSION=$(date -u +%Y%m%d.%H%M%S)" >> $GITHUB_ENV
          sudo find . | cpio --create --format='newc' > ../nd-initrd-bullseye-${{ env.INITRD_VERSION }}
      
      - name: compress new initrd file
        run: gzip nd-initrd-bullseye-${{ env.INITRD_VERSION }}
      
      - name: upload initrd
        uses: actions/upload-artifact@v2
        with:
          name: nd-initrd-bullseye-${{ env.INITRD_VERSION }}
